<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4vrssv1\appDevProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4vrssv1/appDevProjectContainer.php') {
    touch(__DIR__.'/Container4vrssv1.legacy');

    return;
}

if (!\class_exists(appDevProjectContainer::class, false)) {
    \class_alias(\Container4vrssv1\appDevProjectContainer::class, appDevProjectContainer::class, false);
}

return new \Container4vrssv1\appDevProjectContainer([
    'container.build_hash' => '4vrssv1',
    'container.build_id' => 'c7585842',
    'container.build_time' => 1582174161,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4vrssv1');
