<?php

namespace EventBundle\Repository;

/**
 * titre_eventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class titre_eventRepository extends \Doctrine\ORM\EntityRepository
{
}
